//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoapTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoapTable()
        {
            this.SoapStockTable = new HashSet<SoapStockTable>();
        }
    
        public int IdSoap { get; set; }
        public string Name { get; set; }
        public int IdRecipe { get; set; }
        public System.DateTime TimeOfProduction { get; set; }
        public System.DateTime TimeOfReadyToUse { get; set; }
        public System.DateTime BestBeforeDate { get; set; }
        public int InStock { get; set; }
        public string Others { get; set; }
    
        public virtual RecipeTable RecipeTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoapStockTable> SoapStockTable { get; set; }
    }
}
