//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoapStockTable
    {
        public int TransactionNumber { get; set; }
        public System.DateTime Date { get; set; }
        public int IdSoap { get; set; }
        public int Quantity { get; set; }
        public Nullable<double> SellingPrice { get; set; }
    
        public virtual SoapTable SoapTable { get; set; }
    }
}
